  environment:
    name: dev-tre

  resources:
    - name: jupyterhub-main
      type: Jupyter
      url: https://jupyter.example.org
      enabled: true
      auth: oidc

    - name: keycloak-main
      type: Keycloak
      url: https://auth.example.org
      enabled: true
      somethingspecific: realm-config