apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: cr8tor-operator
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - service-account.yaml
  - rbac.yaml
  - deployment.yaml
  - configmaps.yaml

commonLabels:
  app.kubernetes.io/name: cr8tor-operator
  app.kubernetes.io/component: operator
  app.kubernetes.io/part-of: k8tre

namePrefix: ""
namespace: cr8tor
