[[metadata_sources]]
file = "metadata/dataset_1.toml"

[project]
description = "P002 created using CR8TOR."
reference = "cr8-cr8-p002"
name = "P002"
project_name = "Pr002"
project_start_time = "20250201_010101"
destination_type = "LSC"
destination_format = "DUCKDB"
id = "15a23742-647e-4c68-b2e6-1a8463053789"

[repository]
codeRepository = "https://github.com/lsc-sde-crates/"
description = "This LSC-DIP RO-Crate is versioned and stored in a Git repository on GitHub."
name = "Github Repo"

[requesting_agent]
name = "Mike Harding"

[requesting_agent.affiliation]
name = "Someuni"
url = "https://someuni.com"
